Update the regular expression for core types.
ybiquitous/rbs-mode pull request #13
Opened 2024-08-04 07:36 UTC by gemmaro

Hello,

This updates the regular expression for core types.
It makes, for example, not to recognize `StringScanner` as `String` (core type) and `Scanner`.

Thanks,

2024-08-05 00:40 UTC, ybiquitous requested changes
@gemmaro Thanks for the pull request. The regex fix looks good, but the CI fails due to the new test.

It'd be helpful if you could separate the bug fix from the test addition. 🙏🏼

2024-08-05 00:41 UTC, ybiquitous commented
Ref https://github.com/leotaku/elisp-check#tests

2024-08-05 03:17 UTC, gemmaro commented
@ybiquitous Thank you for the pointer.  I tweaked the GitHub Actions settings and splitted into several commits.

2024-08-05 03:58 UTC, ybiquitous requested changes
Thanks for separating commits. The tests are executed on CI, but they still fails due to incorrect expectations. Can you take a look again?

2024-08-05 03:58 UTC, ybiquitous commented on .github/workflows/test.yml
>        - uses: leotaku/elisp-check@6a1fc6b11ae66dda13859f8b3474a36dfe3ef225
[suggest] To line the existing file, it seems required to have two jobs for `leotaku/elisp-check`. For example:

```suggestion
      - uses: leotaku/elisp-check@6a1fc6b11ae66dda13859f8b3474a36dfe3ef225
        with:
          file: rbs-mode.el
      - uses: leotaku/elisp-check@6a1fc6b11ae66dda13859f8b3474a36dfe3ef225
```

2024-08-05 11:20 UTC, gemmaro commented
@ybiquitous I updated the test file to load `rbs-mode.el`.  Let's see if it works...
I also used your suggestion to avoid shadowing the source file.

2024-08-06 00:15 UTC, ybiquitous approved these changes
Thank you. LGTM 👍🏼

2024-08-06 00:16 UTC, merged

2024-08-06 01:27 UTC, ybiquitous commented
https://github.com/ybiquitous/rbs-mode/releases/tag/v0.3.2 is released! 🌮 
Thanks for your contribution. 😄